language: rust

matrix:
  include:
    - rust: 1.9.0
      os: linux
      dist: trusty
    - rust: 1.9.0
      os: osx
    - rust: 1.10.0
      os: linux
      dist: trusty
    - rust: 1.10.0
      os: osx
    - rust: 1.11.0
      os: linux
      dist: trusty
    - rust: 1.11.0
      os: osx
    - rust: stable
      os: linux
      dist: trusty
    - rust: stable
      os: osx
    - rust: beta
      os: linux
      dist: trusty
    - rust: beta
      os: osx
    - rust: nightly
      os: linux
      dist: trusty
    - rust: nightly
      os: osx
  allow_failures:
    - rust: nightly
  fast_finish: true

cache:
  directories:
    - llvm-3.8.0

sudo: required

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libdw-dev
      - libdw1
      - libelf-dev

env:
  global:
    secure: AAAAB3NzaC1yc2EAAAADAQABAAACAQC3pVIUxsVNw0SxKj0OqbHEN7sbWivl7p+K/3M3T8ey7qznogLgX7zrEEG4Cf+CcZC+alSS4gnFXxnxNDC6Nmfo2QZYcqtxHNdv405s/VtqI5qt7cyXP7goaL+a7Cv+5MUecMf0ceVL8g7Lf+KScAYmU4n8yxeTPM+HPltGcekkY+vAQeCOV2q1MifbmXn6+N1WDxYgULggHnIwKOAzhqVfIk59ungd2YzqAJzNW06kWDVg2T+s4WAgHp8Ql2ZsDDYRaUfa+zKrps2lbWmP8vjHspSgUiLZml7dRoezK8LQQ7urYRLAm16dVVAXzGqXueOM8G0JExGh3EUWV7d2LSPjNEYCJ0G3T/CNYRFgtVToZ8RH+8P92ZqsSHg8iDi/LPtYRmmiEzDHCksCOsnlW3AwSfveB1ant29oQE8POQfqf0eyVMG/7NjflwSbdc8/qbQuReqwN+Q24HfaIvx9kJD2S8ogntdVHWlezp7TUmq+DIWsuRqoquYkzrOPXt0RIrkC7EolXwSrBj3FSEKG/XmPDM4M8VcCd+IMHxEGxoonvD+u1Cx57mnsWmtv1P1ezzrRxorFmJiMhF8LPedL9t2mJB0/jEL1qX84/yePqKx7vJqaxVLcgIYhv3toEjDEFTj0vie+wzHxaoXmNaThKqZWlksvZXr4ebFsyhOJf45Y8w==

notifications:
  irc: "chat.freenode.net#taguavm"

install:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          if [[ ! -n "$(ls -A llvm-3.8.0)" ]]; then
              curl 'http://llvm.org/releases/3.8.0/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz' --verbose > llvm-3.8.0.tar.xz;
              mkdir llvm-3.8.0;
              tar -xvf llvm-3.8.0.tar.xz --strip 1 -C llvm-3.8.0;
          fi

          export PATH="$PWD/llvm-3.8.0/bin/:$PATH";

          # llvm-config gives compiler arguments for the compiler it was
          # compiled with. On Ubuntu cc is gcc, so override that to avoid:
          # “unrecognized command line option ‘-Wcovered-switch-default’”.
          cc --version;
          sudo rm $(which cc);
          sudo ln -s $PWD/llvm-3.8.0/bin/clang /usr/bin/cc;
          cc --version;
      fi
  - |
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          brew update;
          brew rm -f llvm;
          brew install llvm38;
          export CXX="clang++-3.8 -stdlib=libc++"
          export CXXFLAGS="$CXXFLAGS -nostdinc++ -I/usr/local/opt/llvm38/lib/llvm-3.8/include/c++/v1"
          export LDFLAGS="$LDFLAGS -L/usr/local/opt/llvm38/lib/llvm-3.8/lib"
          export PATH="/usr/local/opt/llvm38/lib/llvm-3.8/bin:$PATH";
      fi
  - llvm-config --version

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH="$HOME/.local/bin:$HOME/Library/Python/2.7/bin:$PATH"

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo --only stable doc

after_success:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          travis-cargo --only stable doc-upload;
          travis-cargo coveralls --no-sudo;
      fi
